### ISSUE TITLE
Hello, have a question, can't get this to run?

### ISSUE THREAD

**Issue by ghost** [deckerego/docmag#49]
Installed Docker on windows 10
Tried the pull command  -- docker pull deckerego/docmagui

Got 
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
deckerego/docmagui   latest              ddc010bdbaa7        19 months ago       500MB

C:\Users\User\Documents\GitHub>docker run ddc010bdbaa7

Tried running it and connecting to localhost:1080, nothing.

How can I get this up and running on windows 10 to search through pdfs on my desktoP?

**Comment by deckerego** [comment]
Walking through the README is the best way to get up and running. There are several Docker images that need to be running - Docker Compose is the easiest way to orchestrate them all.
